<a href="https://colab.research.google.com/github/hafizzx/python-projects/blob/main/Batch_Gradient_Descent_with_Multiple_variables_in_LR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [9]:
df = pd.read_csv("/content/global_university_students_performance_habits_10000.csv")
df.head(10)

  student_id  age  ... final_exam_score assignment_score
0     S00001   23  ...              100              100
1     S00002   26  ...              100               83
2     S00003   18  ...              100              100
3     S00004   20  ...              100               98
4     S00005   28  ...              100               94
5     S00006   18  ...               96               94
6     S00007   27  ...              100               97
7     S00008   19  ...              100               93
8     S00009   20  ...              100              100
9     S00010   21  ...               92               99

[10 rows x 27 columns]

In [5]:
df.shape

(10000, 27)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 27 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   student_id                      10000 non-null  object
 1   age                             10000 non-null  int64
 2   gender                          10000 non-null  object
 3   country                         10000 non-null  object
 4   major                           10000 non-null  object
 5   university_year                 10000 non-null  int64
 6   GPA                             10000 non-null  float64
 7   study_hours_per_day             10000 non-null  float64
 8   class_attendance_percent        10000 non-null  int64
 9   sleep_hours                     10000 non-null  float64
 10  screen_time_hours               10000 non-null  float64
 11  social_media_hours              10000 non-null  float64
 12  gaming_hours                    10000 non-null  float64
 13  exercise_hours_per_week         10000 non-null  float64
 14  part_time_job                   10000 non-null  object
 15  relationship_status             10000 non-null  object
 16  family_income_level             10000 non-null  object
 17  internet_quality                10000 non-null  object
 18  mental_stress_level             10000 non-null  float64
 19  AI_tool_usage_hours             10000 non-null  float64
 20  favorite_AI_tool                8280 non-null   object
 21  note_taking_method              10000 non-null  object
 22  exam_preparation_days           10000 non-null  int64
 23  coffee_consumption_per_day      10000 non-null  int64
 24  extracurricular_hours_per_week  10000 non-null  float64
 25  final_exam_score                10000 non-null  int64
 26  assignment_score                10000 non-null  int64
dtypes: float64(10), int64(7), object(10)
memory usage: 2.1+ MB

In [7]:
df.isnull().sum()

student_id                           0
age                                  0
gender                               0
country                              0
major                                0
university_year                      0
GPA                                  0
study_hours_per_day                  0
class_attendance_percent             0
sleep_hours                          0
screen_time_hours                    0
social_media_hours                   0
gaming_hours                         0
exercise_hours_per_week              0
part_time_job                        0
relationship_status                  0
family_income_level                  0
internet_quality                     0
mental_stress_level                  0
AI_tool_usage_hours                  0
favorite_AI_tool                  1720
note_taking_method                   0
exam_preparation_days                0
coffee_consumption_per_day           0
extracurricular_hours_per_week       0
final_exam_score                     0
assignment_score                     0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [29]:
df['part_time_job'] = df['part_time_job'].map({
    'Yes': 1,
    'No': 0
})

In [30]:
X = df.drop(columns=['final_exam_score','student_id','gender','country','major','relationship_status','family_income_level','internet_quality','favorite_AI_tool','note_taking_method'])
y = df['final_exam_score']

print(X.shape)
print(y.shape)

(10000, 17)
(10000,)

In [31]:
X.head(20)

    age  university_year  ...  extracurricular_hours_per_week  assignment_score
0    23                4  ...                             7.6               100
1    26                2  ...                             5.2                83
2    18                3  ...                             4.6               100
3    20                4  ...                             4.0                98
4    28                2  ...                             1.4                94
5    18                2  ...                             1.7                94
6    27                1  ...                             3.8                97
7    19                1  ...                             0.0                93
8    20                3  ...                             4.7               100
9    21                2  ...                             4.1                99
10   26                2  ...                             4.2                81
11   25                3  ...                             5.3                88
12   24                2  ...                             1.2                94
13   26                2  ...                             5.6                87
14   26                4  ...                             6.1                85
15   19                3  ...                             2.0                99
16   21                2  ...                             1.5                98
17   24                4  ...                             5.0               100
18   25                1  ...                             0.3                67
19   21                4  ...                             4.2                75

[20 rows x 17 columns]

In [24]:
y

0       100
1       100
2       100
3       100
4       100
       ...
9995    100
9996     85
9997    100
9998     97
9999    100
Name: final_exam_score, Length: 10000, dtype: int64

In [32]:
X_train,X_test, y_train, y_test = train_test_split(X,y, test_size= 0.2, random_state = 2)

In [33]:
reg = LinearRegression()

In [34]:
reg.fit(X_train, y_train)

LinearRegression()

In [36]:
print(reg.coef_)

[ 1.94232617e-03 -8.95052356e-03  8.39732014e+00  4.89358429e-01
  1.23228299e-01 -2.00956084e-01  3.33403564e-03  1.65683505e-01
  4.39199735e-02  9.40498217e-03  1.28822558e-01  5.94708947e-02
 -1.03406512e-02  1.97717119e-03 -1.44299479e-02 -1.75384345e-02
  2.02962683e-02]

In [37]:
print(reg.intercept_)

51.55030658398454

In [41]:
y_pred = reg.predict(X_test)
y_pred

array([ 90.68009161,  98.27954143,  92.33965249, ...,  93.88588125,
        88.97985348, 101.72317251])

In [42]:
r2_score(y_test, y_pred)

0.5222577033586848

In [52]:
class GDRegressor:
  def __init__(self, learning_rate = 0.01, epoch = 10):
    self.coef_ = None
    self.intercept_ = None
    self.lr = learning_rate
    self.epoch = epoch

  def fit(self, X_train, y_train):
    self.intercept_ = 0
    self.coef_ = np.ones(X_train.shape[1])
    for i in range(self.epoch):
      y_hat = np.dot(X_train, self.coef_) + self.intercept_
      intercept_der = -2* np.mean(y_train - y_hat)
      self.intercept_ = self.intercept_ - (self.lr * intercept_der)

    #second coef
      coef_der = -2 * np.dot((y_train - y_hat),X_train)/ X_train.shape[0]
      self.coef_ = self.coef_ - self.lr* coef_der

      print(self.intercept_, self.coef_)

  def predict(self, X_test):
    return np.dot(X_test, self.coef_) + self.intercept_

In [58]:
gd = GDRegressor(learning_rate=0.0001, epoch=100)

In [59]:
gd.fit(X_train, y_train)

-0.0327629855 [ 0.24669757  0.91728547  0.88083296  0.88260152 -1.98520368  0.76940317
  0.80901396  0.90752983  0.94792807  0.89890136  0.98857046  0.86701109
  0.95885439  0.5987093   0.94084867  0.86724533 -2.06167487]
0.05098845891332337 [2.16656177 1.12772871 1.18605901 1.18349475 5.65510665 1.35839849
 1.29253274 1.14021813 1.08009358 1.15544895 1.01767454 1.20523858
 1.06361618 1.60867356 1.09088119 1.20399598 5.76880924]
-0.16326780093703316 [ -2.7506886    0.58836635   0.4058162    0.41451757 -13.88145056
  -0.14886983   0.05088611   0.54125889   0.74103757   0.49725
   0.94310624   0.33824443   0.79519192  -0.99083329   0.70588682
   0.33990046 -14.25950728]
0.3846894558345686 [ 9.81934578  1.96678071  2.40187105  2.38193499 36.09209047  3.70546823
  3.22169877  2.06940915  1.60722422  2.17869723  1.13370054  2.55384598
  1.48126439  5.64167465  1.6893297   2.54720853 36.96651429]
-1.0168623795773941 [-22.33773184  -1.55989043  -2.70299771  -2.64951828 -91.72004702
  -6.15354488  -4.89320184  -1.84292946  -0.60923066  -2.12395364
   0.64609001  -3.11488615  -0.27397417 -11.33840846  -0.82727106
  -3.10119206 -94.05431396]
2.5678362751731516 [ 59.90353517   7.45915406  10.35413021  10.21999803 235.18932989
  19.06201603  15.85732301   8.15985212   5.05877319   8.87889721
   1.89312094  11.38210934   4.21491708  32.07540382   5.60817418
  11.34292    241.05674987]
-6.600772772872556 [-150.45125156  -15.60991408  -23.04159222  -22.6957151  -600.94031651
  -45.43248552  -37.2210969   -17.42799223   -9.43926264  -19.26505505
   -1.29653182  -25.69867144   -7.2667712   -78.9798664   -10.85298306
  -25.60348359 -616.05541527]
16.8496912586194 [ 387.56547979   43.39262825   62.37491164   61.49322052 1537.6291888
  119.52400176   98.53242425   48.01414092   27.64128373   52.71658197
    6.86149973   69.14077867   22.09941386  205.04976274   31.2483889
   68.89138723 1576.1759314 ]
-43.129486920185286 [ -988.52391218  -107.51898155  -156.09403235  -153.83583575
 -3932.17474385  -302.38517406  -248.68857006  -119.37064343
   -67.20045438  -131.39250513   -14.00438481  -173.43149119
   -53.01080537  -521.42722715   -76.43533063  -172.80043824
 -4030.88361261]
110.27892131280413 [ 2531.08654762   278.46580618   402.6833391    396.9107961
 10057.92062433   776.72907475   639.39199153   308.74484302
   175.37478766   339.50039731    39.36405839   446.9925425
   139.09776165  1336.66368046   198.98554358   445.37080188
 10310.26483418]
-282.09305060237773 [ -6471.01040788   -708.76668029  -1026.49837036  -1011.73060103
 -25724.47282843  -1983.31690787  -1632.0521521    -786.24777742
   -445.05972014   -864.90206571    -97.1362733   -1139.86482109
   -352.25784675  -3415.78193319   -505.4583168   -1135.72548889
 -26370.02021679]
721.4747734921337 [16553.60216783  1816.27190751  2628.91308833  2591.14512432
 65795.98366547  5076.03836396  4177.60452303  2014.40572824
  1141.82156845  2215.59019546   251.98982746  2918.83060057
   904.47950709  8739.50930212  1296.29303923  2908.23397806
 67446.96439784]
-1845.3457558816694 [ -42336.34275887   -4642.00796329   -6720.51440508   -6623.91186615
 -168285.43339473  -12979.64067961  -10681.73062928   -5148.81570435
   -2916.93790307   -5663.37171248    -640.96841057   -7462.07657831
   -2309.87191478  -22350.03480223   -3312.03878829   -7434.98400989
 -172508.27609556]
4719.798455776101 [108286.1733926   11876.30162985  17192.47075958  16945.39463318
 430423.4609056   33201.28008812  27323.91302276  13172.51682062
   7464.13024638  14488.60843685   1642.94635916  19089.11683811
   5911.45844662  57167.5239428    8474.66763366  19019.81105925
 441224.06283488]
-12071.838659265828 [ -276960.30220798   -30372.49869844   -43969.653421     -43337.7042115
 -1100891.33037902   -84915.43470506   -69882.93972843   -33687.86902675
   -19087.47772562   -37054.01411625    -4198.61134598   -48820.74188181
   -15116.19827311  -146214.16046578   -21672.13467901   -48643.49097148
 -1128516.12356155]
30876.04900863737 [ 708382.7082059    77687.04913508  112464.41135885  110848.08188445
 2815744.98817374  217191.10532652  178742.54490652   86166.70579551
   48823.43846661   94776.29623047   10742.31195499  124871.96810273
   38666.13548328  373974.15874964   55434.19216416  124418.60129048
 2886400.63460066]
-78971.55219333287 [-1811824.27220362  -198696.32623846  -287646.22670935  -283512.14475573
 -7201816.46597001  -555505.30777582  -457165.63974109  -220384.75474334
  -124871.97903671  -242405.44247496   -27472.01425083  -319381.02421529
   -98892.67565049  -956508.96330504  -141780.28219944  -318221.46407002
 -7382532.22132726]
201985.11737756612 [ 4634096.72640359   508208.07323719   735714.78584049   725141.06883642
 18420051.22551223  1420816.50885192  1169293.59336679   563680.40524739
   319387.93546915   620002.63111972    70268.57990716   816882.66856169
   252940.81890935  2446461.16255016   362634.20818212   813916.85246412
 18882266.86434447]
-516616.3752957419 [-11852603.7313079   -1299837.83538229  -1881730.64491125
  -1854686.296744   -47112873.81293282  -3634012.08710728
  -2990693.19658854  -1441719.20384221   -816893.46496592
  -1585774.26127314   -179722.05742356  -2089333.39463811
   -646941.98105401  -6257298.81503974   -927504.25550426
  -2081747.75709209 -48295080.64491494]
1321347.129987564 [3.03153490e+07 3.32459230e+06 4.81289667e+06 4.74372547e+06
 1.20500366e+08 9.29469816e+06 7.64928456e+06 3.68748151e+06
 2.08936789e+06 4.05593045e+06 4.59677767e+05 5.34388114e+06
 1.65468383e+06 1.60042653e+07 2.37227655e+06 5.32447938e+06
 1.23524091e+08]
-3379603.092470633 [-7.75374164e+07 -8.50328992e+06 -1.23099187e+07 -1.21329999e+07
 -3.08203194e+08 -2.37730005e+07 -1.95645343e+07 -9.43144995e+06
 -5.34396249e+06 -1.03738300e+07 -1.17571202e+06 -1.36680151e+07
 -4.23217320e+06 -4.09340278e+07 -6.06755660e+06 -1.36183914e+07
 -3.15936959e+08]
8643994.182602644 [1.98317071e+08 2.17488263e+07 3.14850220e+07 3.10325176e+07
 7.88289795e+08 6.08040898e+07 5.00401163e+07 2.41227766e+07
 1.36682301e+07 2.65330973e+07 3.00711640e+06 3.49586185e+07
 1.08246121e+07 1.04696764e+08 1.55189632e+07 3.48316960e+07
 8.08070409e+08]
-22108701.462429974 [-5.07234596e+08 -5.56268626e+07 -8.05290825e+07 -7.93717142e+07
 -2.01620493e+09 -1.55518318e+08 -1.27987356e+08 -6.16987037e+07
 -3.49591614e+07 -6.78635691e+07 -7.69128329e+06 -8.94134834e+07
 -2.76860536e+07 -2.67782397e+08 -3.96927723e+07 -8.90888543e+07
 -2.06679771e+09]
56547317.0151058 [1.29735144e+09 1.42276556e+08 2.05968842e+08 2.03008647e+08
 5.15683745e+09 3.97768441e+08 3.27352635e+08 1.57806474e+08
 8.94148787e+07 1.73574321e+08 1.96719610e+07 2.28692430e+08
 7.08124867e+07 6.84905723e+08 1.01522012e+08 2.27862128e+08
 5.28623835e+09]
-144630794.788608 [-3.31822939e+09 -3.63900046e+08 -5.26805491e+08 -5.19234215e+08
 -1.31896178e+10 -1.01737038e+09 -8.37268223e+08 -4.03620841e+08
 -2.28695992e+08 -4.43950183e+08 -5.03148744e+07 -5.84925501e+08
 -1.81116746e+08 -1.75178000e+09 -2.59662348e+08 -5.82801841e+08
 -1.35205858e+10]
369921472.8227739 [8.48701899e+09 9.30745361e+08 1.34740782e+09 1.32804280e+09
 3.37350206e+10 2.60212323e+09 2.14147682e+09 1.03233904e+09
 5.84934618e+08 1.13548920e+09 1.28690110e+08 1.49606108e+09
 4.63241414e+08 4.48051909e+09 6.64137114e+08 1.49062941e+09
 3.45815359e+10]
-946146332.6170299 [-2.17072068e+10 -2.38056283e+09 -3.44625835e+09 -3.39672854e+09
 -8.62838963e+10 -6.65543780e+09 -5.47724474e+09 -2.64040849e+09
 -1.49608439e+09 -2.90423515e+09 -3.29150059e+08 -3.82646807e+09
 -1.18483028e+09 -1.14598017e+10 -1.69866023e+09 -3.81257551e+09
 -8.84490244e+10]
2419953823.846015 [5.55204160e+10 6.08875386e+09 8.81447804e+09 8.68779590e+09
 2.20687897e+11 1.70225805e+10 1.40091219e+10 6.75335982e+09
 3.82652770e+09 7.42814798e+09 8.41865492e+08 9.78693858e+09
 3.03043459e+09 2.93106784e+10 4.34465492e+09 9.75140563e+09
 2.26225635e+11]
-6189503999.304822 [-1.42004295e+11 -1.55731758e+10 -2.25447472e+10 -2.22207329e+10
 -5.64452351e+11 -4.35385706e+10 -3.58310623e+10 -1.72730352e+10
 -9.78709110e+09 -1.89989376e+10 -2.15323523e+09 -2.50320047e+10
 -7.75092766e+09 -7.49677780e+10 -1.11123025e+10 -2.49411222e+10
 -5.78616195e+11]
15830863952.69867 [3.63203687e+11 3.98314352e+10 5.76625890e+10 5.68338592e+10
 1.44369700e+12 1.11358388e+11 9.16449320e+10 4.41791573e+10
 2.50323948e+10 4.85934892e+10 5.50731916e+09 6.40242354e+10
 1.98245096e+10 1.91744717e+11 2.84218815e+10 6.37917858e+10
 1.47992380e+12]
-40490522910.68034 [-9.28964286e+11 -1.01876666e+11 -1.47483320e+11 -1.45363682e+11
 -3.69253673e+12 -2.84820801e+11 -2.34399792e+11 -1.12996813e+11
 -6.40252331e+10 -1.24287328e+11 -1.40860431e+10 -1.63754472e+11
 -5.07050507e+10 -4.90424521e+11 -7.26945067e+10 -1.63159937e+11
 -3.78519382e+12]
103562411405.78697 [2.37600739e+12 2.60569448e+11 3.77217364e+11 3.71795976e+11
 9.44438303e+12 7.28484764e+11 5.99523196e+11 2.89011394e+11
 1.63757024e+11 3.17889089e+11 3.60278033e+10 4.18834008e+11
 1.29688059e+11 1.25435639e+12 1.85930382e+11 4.17313368e+11
 9.68137162e+12]
-264881070561.75696 [-6.07710242e+12 -6.66457196e+11 -9.64806997e+11 -9.50940739e+11
 -2.41558521e+13 -1.86324190e+12 -1.53339753e+12 -7.39203022e+11
 -4.18840535e+11 -8.13063361e+11 -9.21481354e+10 -1.07124968e+12
 -3.31702511e+11 -3.20826116e+12 -4.75553225e+11 -1.06736035e+12
 -2.47619966e+13]
677485012076.5863 [1.55433750e+13 1.70459429e+12 2.46768211e+12 2.43221645e+12
 6.17833040e+13 4.76560465e+12 3.92196333e+12 1.89065594e+12
 1.07126638e+12 2.07956816e+12 2.35686833e+11 2.73993005e+12
 8.48393881e+11 8.20575380e+12 1.21632015e+12 2.72998232e+12
 6.33336370e+13]
-1732800085015.6323 [-3.97552138e+13 -4.35983245e+12 -6.31157841e+12 -6.22086807e+12
 -1.58022853e+14 -1.21889636e+13 -1.00311863e+13 -4.83572139e+12
 -2.73997275e+12 -5.31890126e+12 -6.02815054e+11 -7.00790562e+12
 -2.16993286e+12 -2.09878162e+13 -3.11097606e+12 -6.98246237e+12
 -1.61988132e+14]
4431974259366.602 [1.01681715e+14 1.11511220e+13 1.61430931e+13 1.59110837e+13
 4.04174274e+14 3.11756522e+13 2.56567159e+13 1.23683008e+13
 7.00801483e+12 1.36041276e+13 1.54181710e+12 1.79240858e+13
 5.55002661e+12 5.36804342e+13 7.95692817e+12 1.78590097e+13
 4.14316249e+14]
-11335638776536.154 [-2.60070822e+14 -2.85211700e+13 -4.12891098e+13 -4.06957005e+13
 -1.03375455e+15 -7.97378124e+13 -6.56220562e+13 -3.16343422e+13
 -1.79243651e+13 -3.47952103e+13 -3.94349802e+12 -4.58443460e+13
 -1.41952758e+13 -1.37298183e+14 -2.03513961e+13 -4.56779013e+13
 -1.05969463e+15]
28993107575149.523 [6.65181863e+14 7.29484562e+13 1.05604953e+14 1.04087193e+14
 2.64402894e+15 2.03945011e+14 1.67841211e+14 8.09110017e+13
 4.58450604e+13 8.89955384e+13 1.00862655e+13 1.17255859e+14
 3.63071871e+13 3.51166887e+14 5.20526657e+13 1.16830143e+14
 2.71037575e+15]
-74155528720989.94 [-1.70133238e+15 -1.86579908e+14 -2.70105269e+14 -2.66223302e+14
 -6.76261983e+15 -5.21629152e+14 -4.29286639e+14 -2.06945671e+14
 -1.17257686e+14 -2.27623451e+14 -2.57975917e+13 -2.99904733e+14
 -9.28627139e+13 -8.98177821e+14 -1.33134847e+14 -2.98815884e+14
 -6.93231474e+15]
189667231276818.47 [4.35148947e+15 4.77214513e+14 6.90846920e+14 6.80918031e+14
 1.72967195e+16 1.33416832e+15 1.09798433e+15 5.29303926e+14
 2.99909406e+14 5.82191382e+14 6.59823734e+13 7.67064861e+14
 2.37514507e+14 2.29726500e+15 3.40518344e+14 7.64279917e+14
 1.77307473e+16]
-485110945072820.6 [-1.11297832e+16 -1.22056921e+15 -1.76697577e+15 -1.74158070e+15
 -4.42397344e+16 -3.41239575e+15 -2.80830912e+15 -1.35379805e+15
 -7.67076815e+14 -1.48906803e+15 -1.68762792e+14 -1.96191802e+15
 -6.07489686e+14 -5.87570339e+15 -8.70942095e+14 -1.95479499e+15
 -4.53498453e+16]
1240765879510195.5 [2.84665918e+16 3.12184388e+15 4.51938524e+15 4.45443240e+15
 1.13151751e+17 8.72786783e+15 7.18279842e+15 3.46260262e+15
 1.96194860e+15 3.80858199e+15 4.31643764e+14 5.01798809e+15
 1.55377338e+15 1.50282577e+16 2.22760431e+15 4.99976953e+15
 1.15991076e+17]
-3173500790681216.5 [-7.28088620e+16 -7.98472474e+15 -1.15592094e+16 -1.13930798e+16
 -2.89407678e+17 -2.23232246e+16 -1.83714082e+16 -8.85628169e+15
 -5.01806628e+15 -9.74119144e+15 -1.10401313e+15 -1.28344835e+16
 -3.97407855e+15 -3.84377008e+16 -5.69753260e+15 -1.27878859e+16
 -2.96669806e+17]
8116847372068272.0 [1.86222868e+17 2.04224912e+16 2.95649331e+16 2.91400243e+16
 7.40216595e+17 5.70960019e+16 4.69884605e+16 2.26516681e+16
 1.28346835e+16 2.49149975e+16 2.82372896e+15 3.28266953e+16
 1.01644812e+16 9.83119183e+16 1.45725511e+16 3.27075130e+16
 7.58790904e+17]
-2.0760420622838188e+16 [-4.76301315e+17 -5.22345054e+16 -7.56180841e+16 -7.45312970e+16
 -1.89324835e+18 -1.46034163e+17 -1.20182154e+17 -5.79360603e+16
 -3.28272068e+16 -6.37249665e+16 -7.22223769e+15 -8.39606771e+16
 -2.59976435e+16 -2.51451910e+17 -3.72721424e+16 -8.36558452e+16
 -1.94075577e+18]
5.309882577320683e+16 [1.21823353e+18 1.33599938e+17 1.93408002e+17 1.90628332e+17
 4.84235199e+18 3.73510862e+17 3.07389305e+17 1.48182777e+17
 8.39619855e+16 1.62989034e+17 1.84722818e+16 2.14745811e+17
 6.64940450e+16 6.43137315e+17 9.53307754e+16 2.13966144e+17
 4.96386148e+18]
-1.3581060565756114e+17 [-3.11586992e+18 -3.41707904e+17 -4.94678696e+17 -4.87569147e+17
 -1.23852599e+19 -9.55326895e+17 -7.86208115e+17 -3.79006359e+17
 -2.14749158e+17 -4.16876250e+17 -4.72464644e+16 -5.49254305e+17
 -1.70071492e+17 -1.64494915e+18 -2.43827056e+17 -5.47260155e+17
 -1.26960441e+19]
3.473621184741997e+17 [7.96944517e+18 8.73984626e+17 1.26523727e+18 1.24705321e+18
 3.16777183e+19 2.44343490e+18 2.01088063e+18 9.69382701e+17
 5.49262865e+17 1.06624234e+18 1.20842050e+17 1.40482504e+18
 4.34991019e+17 4.20727835e+18 6.23635261e+17 1.39972461e+18
 3.24726096e+19]
-8.884463828629306e+17 [-2.03834107e+19 -2.23538618e+18 -3.23609114e+18 -3.18958187e+18
 -8.10219444e+19 -6.24956144e+18 -5.14321951e+18 -2.47938537e+18
 -1.40484693e+18 -2.72712278e+18 -3.09077117e+17 -3.59311409e+18
 -1.11257439e+18 -1.07609352e+19 -1.59506884e+18 -3.58006875e+18
 -8.30550340e+19]
2.272374946034457e+18 [5.21345495e+19 5.71743625e+18 8.27693441e+18 8.15797787e+18
 2.07229429e+20 1.59844726e+19 1.31547873e+19 6.34151177e+18
 3.59317008e+18 6.97514853e+18 7.90525022e+17 9.19009025e+18
 2.84562605e+18 2.75231910e+19 4.07969974e+18 9.15672424e+18
 2.12429452e+20]
-5.812042228958863e+18 [-1.33344281e+20 -1.46234586e+19 -2.11698744e+19 -2.08656199e+19
 -5.30029692e+20 -4.08834069e+19 -3.36459347e+19 -1.62196535e+19
 -9.19023346e+18 -1.78403031e+19 -2.02192196e+18 -2.35054486e+19
 -7.27824377e+18 -7.03959302e+19 -1.04346280e+19 -2.34201086e+19
 -5.43329766e+20]
1.4865431838240698e+19 [3.41054012e+20 3.74023482e+19 5.41460838e+19 5.33678934e+19
 1.35565434e+21 1.04567289e+20 8.60560417e+19 4.14849280e+19
 2.35058149e+19 4.56300556e+19 5.17145987e+18 6.01197705e+19
 1.86155283e+19 1.80051325e+20 2.66885966e+19 5.99014966e+19
 1.38967187e+21]
-3.8021241937356915e+19 [-8.72312169e+20 -9.56638020e+19 -1.38489172e+20 -1.36498799e+20
 -3.46735043e+21 -2.67451241e+20 -2.20105115e+20 -1.06105796e+20
 -6.01207073e+19 -1.16707769e+20 -1.32270175e+19 -1.53768041e+20
 -4.76128452e+19 -4.60516388e+20 -6.82612925e+19 -1.53209763e+20
 -3.55435691e+21]
9.724674359881328e+19 [2.23110855e+21 2.44678836e+20 3.54213075e+20 3.49122306e+20
 8.86842516e+21 6.84058724e+20 5.62961771e+20 2.71386274e+20
 1.53770438e+20 2.98502887e+20 3.38306776e+19 3.93291763e+20
 1.21779140e+20 1.17786050e+21 1.74591572e+20 3.91863859e+20
 9.09096120e+21]
-2.487275180583104e+20 [-5.70649536e+21 -6.25813856e+20 -9.05969042e+20 -8.92948406e+20
 -2.26827274e+22 -1.74961364e+21 -1.43988455e+21 -6.94123339e+20
 -3.93297892e+20 -7.63479366e+20 -8.65285577e+19 -1.00592041e+21
 -3.11473908e+20 -3.01260801e+21 -4.46552006e+20 -1.00226826e+21
 -2.32519068e+22]
6.361691502459946e+20 [1.45954751e+22 1.60064102e+21 2.31719256e+21 2.28388975e+21
 5.80155005e+22 4.47497820e+21 3.68278564e+21 1.77535585e+21
 1.00593609e+21 1.95274742e+21 2.21313667e+20 2.57283769e+21
 7.96655284e+20 7.70533271e+21 1.14214387e+21 2.56349661e+21
 5.94712877e+22]
-1.627126708311511e+21 [-3.73307750e+22 -4.09395168e+21 -5.92667203e+21 -5.84149359e+21
 -1.48385960e+23 -1.14456297e+22 -9.41944274e+21 -4.54081893e+21
 -2.57287778e+21 -4.99453248e+21 -5.66052878e+20 -6.58053431e+21
 -2.03760130e+21 -1.97078916e+22 -2.92125576e+21 -6.55664269e+21
 -1.52109420e+23]
4.161693983238421e+21 [9.54807397e+22 1.04710801e+22 1.51586199e+22 1.49407594e+22
 3.79526041e+23 2.92744309e+22 2.40920624e+22 1.16140303e+22
 6.58063685e+21 1.27744912e+22 1.44779066e+21 1.68310002e+22
 5.21156284e+21 5.04067774e+22 7.47168150e+21 1.67698928e+22
 3.89049516e+23]
-1.0644344242923601e+22 [-2.44210619e+23 -2.67818301e+22 -3.87711277e+22 -3.82139069e+22
 -9.70711890e+23 -7.48750680e+22 -6.16201495e+22 -2.97051481e+22
 -1.68312625e+22 -3.26732533e+22 -3.70300706e+21 -4.30485666e+22
 -1.33295886e+22 -1.28925167e+23 -1.91102830e+22 -4.28922723e+22
 -9.95070035e+23]
2.7224986944786104e+22 [6.24616299e+23 6.84997551e+22 9.91647226e+22 9.77395219e+22
 2.48278503e+24 1.91507593e+23 1.57605554e+23 7.59767113e+22
 4.30492374e+22 8.35682192e+22 9.47116295e+21 1.10105107e+23
 3.40930234e+22 3.29751266e+23 4.88782770e+22 1.09705354e+23
 2.54508574e+24]
-6.963321527641554e+22 [-1.59757804e+24 -1.75201487e+23 -2.53633124e+23 -2.49987895e+23
 -6.35020707e+24 -4.89818030e+23 -4.03106949e+23 -1.94325261e+23
 -1.10106823e+23 -2.13742024e+23 -2.42243469e+22 -2.81615291e+23
 -8.71995583e+22 -8.43403191e+23 -1.25015729e+23 -2.80592845e+23
 -6.50955328e+24]
1.7810053241036455e+23 [4.08611749e+24 4.48111982e+23 6.48716193e+23 6.39392810e+23
 1.62418934e+25 1.25280517e+24 1.03102466e+24 4.97024765e+23
 2.81619680e+23 5.46686923e+23 6.19584931e+22 7.20286046e+23
 2.23029882e+23 2.15716820e+24 3.19752115e+23 7.17670940e+23
 1.66494524e+25]
-4.5552685624153135e+23 [-1.04510426e+25 -1.14613381e+24 -1.65921822e+24 -1.63537185e+24
 -4.15418109e+25 -3.20429362e+24 -2.63704671e+24 -1.27123780e+24
 -7.20297271e+23 -1.39825846e+24 -1.58470933e+23 -1.84227208e+24
 -5.70442432e+23 -5.51737849e+24 -8.17828413e+23 -1.83558343e+24
 -4.25842226e+25]
1.1650988009355142e+24 [2.67305803e+25 2.93146082e+24 4.24377428e+24 4.18278253e+24
 1.06251286e+26 8.19560604e+24 6.74476141e+24 3.25143867e+24
 1.84230079e+24 3.57631878e+24 4.05320327e+23 4.71197024e+24
 1.45901780e+24 1.41117718e+25 2.09175571e+24 4.69486273e+24
 1.08917457e+26]
-2.9799674757740706e+24 [-6.83686739e+25 -7.49778292e+24 -1.08542806e+25 -1.06982823e+25
 -2.71758391e+26 -2.09618613e+25 -1.72510431e+25 -8.31618869e+24
 -4.71204367e+24 -9.14713296e+24 -1.03668581e+24 -1.20517831e+25
 -3.73172266e+24 -3.60936095e+25 -5.35007330e+24 -1.20080273e+25
 -2.78577644e+26]
7.621848163899015e+24 [1.74866221e+26 1.91770425e+25 2.77619402e+25 2.73629441e+25
 6.95075100e+26 5.36140496e+25 4.41229082e+25 2.12702749e+25
 1.20519709e+25 2.33955770e+25 2.65152619e+24 3.08247865e+25
 9.54460871e+24 9.23164475e+25 1.36838562e+25 3.07128724e+25
 7.12516670e+26]
-1.9494363581414826e+25 [-4.47254474e+26 -4.90490274e+25 -7.10065779e+25 -6.99860676e+25
 -1.77779017e+27 -1.37128391e+26 -1.12852945e+26 -5.44028777e+25
 -3.08252668e+25 -5.98387523e+25 -6.78179551e+24 -7.88404048e+25
 -2.44121988e+25 -2.36117324e+26 -3.49991317e+25 -7.85541629e+25
 -1.82240038e+27]
4.986063790202632e+25 [1.14394057e+27 1.25452456e+26 1.81613175e+26 1.79003021e+26
 4.54704517e+27 3.50732612e+26 2.88643423e+26 1.39145973e+26
 7.88416334e+25 1.53049283e+26 1.73457650e+25 2.01649716e+26
 6.24389608e+25 6.03916119e+26 8.95171071e+25 2.00917596e+26
 4.66114451e+27]
-1.2752830845768773e+26 [-2.92585117e+27 -3.20869131e+26 -4.64511126e+26 -4.57835147e+26
 -1.16299551e+28 -8.97067077e+26 -7.38261865e+26 -3.55892970e+26
 -2.01652858e+26 -3.91453398e+26 -4.43651780e+25 -5.15758487e+26
 -1.59699823e+26 -1.54463329e+27 -2.28957465e+26 -5.13885948e+26
 -1.19217864e+28]
3.261785276401007e+26 [7.48343517e+27 8.20685398e+26 1.18807782e+27 1.17100270e+27
 2.97458789e+28 2.29442405e+27 1.88824874e+27 9.10265701e+26

In [60]:
y_pred = gd.predict(X_test)

In [61]:
r2_score(y_test,y_pred)

-2.215178294880106e+84

In [62]:
import numpy as np

print("Actual:", np.array(y_test)[:5])
print("Predicted:", np.array(y_pred)[:5])
print("Max prediction:", np.max(np.abs(y_pred)))
print("All finite:", np.isfinite(y_pred).all())

Actual: [100 100 100 100 100]
Predicted: [8.68827165e+42 1.03374115e+43 9.57977072e+42 1.08627636e+43
 1.06832981e+43]
Max prediction: 1.0967415522638374e+43
All finite: True